apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  namespace: openshift-logging
  name: instance
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 150m
            memory: 128Mi
      type: fluentd
  managementState: Managed