apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: openshift-logging
data:
  application.yml: |
    path:
      config: /usr/share/logstash/pipeline/pipeline.conf
  infrastructure.yml: |
    path:
      config: /usr/share/logstash/pipeline/pipeline.conf
  audit.yml: |
    path:
      config: /usr/share/logstash/pipeline/pipeline.conf