apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: openshift-logging
data:
  application.conf: |
    input {
      tcp {
        port => 5044
        type => syslog
      }
    }
    filter {
    }
    output {
      stdout {}
    }
  infrastructure.conf: |
    input {
      tcp {
        port => 5045
        type => syslog
      }
    }
    filter {
    }
    output {
      stdout {}
    }
  audit.conf: |
    input {
      tcp {
        port => 5046
        type => syslog
      }
    }
    filter {
      #ruby {
      #  path => "/usr/share/logstash/ruby_filter/main.rb"
      #}
      #kv {
      #  field_split_pattern => "\\t"
      #  value_split => ":"
      #}
    }
    output {
      stdout {}
    }
  audit.rb: |
    def filter(event):
      message = event.get("message")
      formate = message[/.* - - - (.*)/, 1]
      event.set("message", formate)
      return [event]
    end