apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: openshift-logging
  labels:
    app: logstash
    app.kubernetes.io/component: logstash
    app.kubernetes.io/instance: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: logstash
  template:
    metadata:
      labels:
        deployment: logstash
        app: logstash
    spec:
      ### CONTAINERS ###
      containers:
        # Application
        - image: docker.elastic.co/logstash/logstash:7.11.1
          name: logstash-application
          ports:
            - containerPort: 5044
              protocol: TCP
          volumeMounts:
          - name: pipeline-application
            mountPath: /usr/share/logstash/pipeline/
          - name: config-application
            mountPath: /usr/share/logstash/config/
        # Infrastructure
        - image: docker.elastic.co/logstash/logstash:7.11.1
          name: logstash-infrastructure
          ports:
            - containerPort: 5045
              protocol: TCP
          volumeMounts:
          - name: pipeline-infrastructure
            mountPath: /usr/share/logstash/pipeline/
          - name: config-application
            mountPath: /usr/share/logstash/config/
        # Audit
        - image: docker.elastic.co/logstash/logstash:7.11.1
          name: logstash-audit
          ports:
            - containerPort: 5046
              protocol: TCP
          volumeMounts:
          - name: pipeline-audit
            mountPath: /usr/share/logstash/pipeline/
          - name: config-application
            mountPath: /usr/share/logstash/config/
          - name: logstash-ruby
            mountPath: /usr/share/logstash/ruby_filter/
      ### VOLUMES ###
      volumes:
        ## Pipelines ##
        # Application
        - name: pipeline-application
          configMap: 
            name: logstash-pipeline
            items:
            - key: application.conf
              path: pipeline.conf
        # Infrastructure
        - name: pipeline-infrastructure
          configMap: 
            name: logstash-pipeline
            items:
            - key: infrastructure.conf
              path: pipeline.conf
        # Audit
        - name: pipeline-audit
          configMap: 
            name: logstash-pipeline
            items:
            - key: audit.conf
              path: pipeline.conf
        ## Configs ##
        # Application
        - name: config-application
          configMap: 
            name: logstash-config
            items:
            - key: application.yml
              path: logstash.yml
        # Infrastructure
        - name: config-infrastructure
          configMap: 
            name: logstash-config
            items:
            - key: infrastructure.yml
              path: logstash.yml
        # Audit
        - name: config-audit
          configMap: 
            name: logstash-config
            items:
            - key: audit.yml
              path: logstash.yml
        ## Ruby Scripts ##
        # Audit
        - name: logstash-ruby
          configMap: 
            name: logstash-ruby